name: dusty_quiche
version: 0.0.1
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  ffi: ^0.1.3
  ffigen: ^0.2.1+1
ffigen:
  output: 'quiche_bindings.g.dart'
  headers:
    entry-points:
      - 'quiche.h'
